# Generated by Django 6.0 on 2025-12-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentRest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Contato')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/', verbose_name='Arquivo')),
                ('tipo_documento', models.CharField(choices=[('AVCB', 'AVCB (Auto de Vistoria do Corpo de Bombeiros)'), ('ALVARA', 'Alvará de Funcionamento'), ('PLANO_ENSINO', 'Plano de Ensino'), ('CONTRATO', 'Contrato'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20, verbose_name='Tipo de Documento')),
                ('outro_tipo_documento', models.CharField(blank=True, max_length=100, verbose_name="Especificar (se 'Outro')")),
                ('responsavel_upload', models.CharField(max_length=100, verbose_name='Responsável pelo Upload')),
                ('data_hora_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora de Envio')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=255, verbose_name='Nome Fantasia')),
                ('endereco', models.TextField(verbose_name='Endereço Principal')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Unidade')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='DocumentRest.escola', verbose_name='Escola')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.AddField(
            model_name='documento',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='DocumentRest.escola', verbose_name='Escola'),
        ),
        migrations.AddField(
            model_name='contato',
            name='escola',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='DocumentRest.escola', verbose_name='Escola'),
        ),
    ]
