# Generated by Django 5.0.6 on 2024-05-21 18:00

from django.db import migrations


def create_sample_schools(apps, schema_editor):
    """
    Cria 20 escolas de exemplo no banco de dados.
    """
    Escola = apps.get_model('DocumentRest', 'Escola')
    
    escolas_para_criar = []
    for i in range(1, 21):
        # Gera um CNPJ único e formatado para cada escola de exemplo
        cnpj = f'{i:02}.{100+i:03}.{200+i:03}/0001-{30+i:02}'
        escolas_para_criar.append(
            Escola(
                razao_social=f'Escola Exemplo {i} LTDA ME',
                nome_fantasia=f'Colégio Exemplo {i}',
                endereco=f'Rua das Amostras, {i * 100}, Bairro Padrão, Carapicuíba, SP',
                cnpj=cnpj
            )
        )
    
    Escola.objects.bulk_create(escolas_para_criar, ignore_conflicts=True)

def delete_sample_schools(apps, schema_editor):
    """
    Deleta as escolas de exemplo para permitir que a migração seja reversível.
    """
    Escola = apps.get_model('DocumentRest', 'Escola')
    cnpjs_to_delete = [f'{i:02}.{100+i:03}.{200+i:03}/0001-{30+i:02}' for i in range(1, 21)]
    Escola.objects.filter(cnpj__in=cnpjs_to_delete).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('DocumentRest', '0001_initial'), # Django ajustará esta dependência para a sua última migração real.
    ]

    operations = [
        migrations.RunPython(create_sample_schools, delete_sample_schools),
    ]