# Generated by Django 6.0 on 2025-12-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentRest', '0002_add_sample_schools'),
        ('DocumentRest', '0002_contato_documento_escola_unidade_delete_todoitem_and_more'),
    ]

    operations = [
    ]
