# Generated by Django 6.0 on 2025-12-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocumentRest', '0003_merge_20251216_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='data_vencimento',
            field=models.DateField(default='2025-12-31', verbose_name='Data de Vencimento'),
            preserve_default=False,
        ),
    ]
